spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: dashboard-main
#  mvc:
#    throw-exception-if-no-handler-found: true
#    static-path-pattern: /statics/**
  redis:
    host: 112.126.99.2
    port: 31379
server:
  port: 20003
  servlet:
    context-path: /main
security:
  oauth2:
    client:
      grantType: client_credentials
      clientId: "Di7hBWKdZbATm4EAqAghniLQz1MGvjdS"
      clientSecret: "9LJWr8ztDW9jkW2C"
      accessTokenUri: https://stageidp.apigw.cdkapps.cn/auth/token
      scope: showroom
api:
  serviceUri: https://stage.apigw.cdkapps.cn/service/
  endpoints:
    repairOrders: /repair-orders
  
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true 
  metrics:
    export:
      prometheus:
        enabled: true
        
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000 
    
swagger.enabled: true

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

feign:
  hystrix:
    enabled: true
    
## 日志设置配置信息
logging:
  config: classpath:logback-boot_dev.xml
  level:
    com.bmw.progress.service: DEBUG

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
#    securePortEnabled: true
    instance-id: ${spring.application.name}:${server.port}


---
spring:
  profiles: k8s
  application:
    name: dashboard-main
#  mvc:
#    throw-exception-if-no-handler-found: true
#    static-path-pattern: /statics/**
  redis:
    host: 112.126.99.2
    port: 31379
server:
  port: 20003
  servlet:
    context-path: /main

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true 
  metrics:
    export:
      prometheus:
        enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000 
    
swagger.enabled: true

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

feign:
  hystrix:
    enabled: true
    
## 日志设置配置信息
logging:
  config: classpath:logback-boot_k8s.xml
  level:
    com.bmw.progress.service: DEBUG

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://bmw-register:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

security:
  oauth2:
    client:
      grantType: client_credentials
      clientId: "Di7hBWKdZbATm4EAqAghniLQz1MGvjdS"
      clientSecret: "9LJWr8ztDW9jkW2C"
      accessTokenUri: https://stageidp.apigw.cdkapps.cn/auth/token
      scope: showroom
api: 
  serviceUri: https://stage.apigw.cdkapps.cn/service/
  endpoints:
    repairOrders: /repair-orders